<<<<<<< HEAD
server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
=======
server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
>>>>>>> b10b9fd0cfd941e3020af41f83c8a4c12de937b9
}